<?php
// Exit if accessed directly
if (!defined('ABSPATH')) {
    exit;
}

function retain_scripts() {
    // Enqueue Google Fonts stylesheet for Source Sans Pro font
    wp_enqueue_style(
        'retain-google-fonts',
        'https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@400;700&display=swap',
        array(),
        null
    );

    // Enqueue Typekit stylesheet for Brandon Grotesque font
    wp_enqueue_style(
        'retain-typekit',
        'https://use.typekit.net/hmd0zsv.css',
        array(),
        null
    );

    // Enqueue compiled stylesheet
    wp_enqueue_style(
        'retain-style',
        get_template_directory_uri() . '/inc/css/bundle.css',
        array(),
        RETAIN_VERSION
    );

    // Enqueue the bundled JS file (generated by Webpack and containing all our scripts)
    wp_enqueue_script(
        'retain-bundle',
        get_template_directory_uri() . '/inc/js/bundle.js', 
        array(), 
        RETAIN_VERSION,
    );
}
add_action('wp_enqueue_scripts', 'retain_scripts');
