name: Deploy to Production
on:
  workflow_dispatch:
  push:
    branches:
      - production
jobs:
  deploy:
    name: Deploy to Production
    uses: pie/.github/.github/workflows/deploy.yaml@main
    with:
      ssh-host: retain-temp.tempurl.host
      ssh-user: theme-github-prd
      destination-path: ~/site/public_html/wp-content/themes/retain-theme
      npm: true
      node_version: 18
    secrets:
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}